Traceback (most recent call last):
  File "/home/aamato/Documents/MARL/UnityPetZoo/python/comm_drones_runner.py", line 31, in <module>
    dronesDQN.train()
  File "/home/aamato/Documents/MARL/UnityPetZoo/python/scripts/dqn_comm_drones.py", line 104, in train
    next_obs, rewards, dones, infos = self.env.step(actions)
  File "/home/aamato/Documents/MARL/UnityPetZoo/python/env/unity_env.py", line 58, in step
    self.unityEnv.set_actions(behavior_name, actions)
  File "/home/aamato/anaconda3/envs/unitypetzoo/lib/python3.10/site-packages/mlagents_envs/environment.py", line 373, in set_actions
    action = action_spec._validate_action(action, num_agents, behavior_name)
  File "/home/aamato/anaconda3/envs/unitypetzoo/lib/python3.10/site-packages/mlagents_envs/base_env.py", line 421, in _validate_action
    raise UnityActionException(
